import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const child = spawn(process.execPath, ['scripts/dev.js'], { env: { ...process.env, PORT: '3100' }, stdio: 'ignore' });
let browser;
try {
  for (let i=0; i<50; i++) { try { if ((await fetch('http://localhost:3100')).ok) break; } catch {} await new Promise(r => setTimeout(r, 100)); }
  browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || '/usr/bin/chromium', headless: true, args: ['--no-sandbox'] });
  const context = await browser.newContext({ permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage();
  let generations = 0, used = 0;
  const reply = 'TEST FIXTURE: Let me check your order details and share a confirmed update.';
  await page.route('**/api/stats?*', route => route.fulfill({ json: { shops_served: used ? 1 : 0, languages: used ? 1 : 0, most_common_request: used ? 'Delivery delay' : null, used } }));
  await page.route('**/api/generate-reply', async route => {
    generations++;
    const body = route.request().postDataJSON();
    assert.match(body.visitor_id, /^[0-9a-f-]{36}$/);
    await new Promise(r => setTimeout(r, 150));
    if (used >= 5) return route.fulfill({ status: 429, json: { error: "You've tried all 5 demo replies. Thanks for testing ReplyWise!" } });
    used++;
    await route.fulfill({ json: { detected_language: 'Hinglish', request_type: 'Delivery delay', reply, follow_up_action: 'TEST FIXTURE: Check tracking.', used } });
  });
  await page.goto('http://localhost:3100');
  await page.locator('#stats-status').filter({ hasText: 'Live from Supabase' }).waitFor();
  await page.locator('#generate-button').click();
  assert.equal(await page.locator('#form-error').textContent(), 'Paste a customer message first.'); assert.equal(generations, 0);
  await page.locator('#customer-message').fill('Hello');
  await page.locator('#generate-button').click();
  assert.equal(await page.locator('#form-error').textContent(), 'Choose your business type.');
  await page.locator('#use-example').click();
  await page.locator('#generate-button').click();
  await page.locator('#loading-result').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#generate-button').isDisabled(), true);
  await page.locator('#result').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#generated-reply').textContent(), reply);
  await page.locator('#copy-reply').click();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), reply);
  assert.equal(await page.locator('#copy-status').textContent(), 'Copied!');
  const id = await page.evaluate(() => localStorage.getItem('replywise_visitor_id'));
  await page.locator('#reset').click();
  assert.equal(await page.locator('#customer-message').inputValue(), '');
  assert.equal(await page.locator('#usage').textContent(), '1 of 5 free demo replies used');
  assert.equal(await page.evaluate(() => localStorage.getItem('replywise_visitor_id')), id);
  await page.reload();
  await page.locator('#usage').filter({ hasText: '1 of 5' }).waitFor();
  await mkdir('test-results', { recursive: true });
  for (const [name, width, height] of [['desktop',1440,1000],['tablet',768,1024],['mobile',390,844],['small-mobile',320,740]]) {
    await page.setViewportSize({ width, height });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `${name}: horizontal overflow`);
    for (const href of ['#try-it','#how-it-works','#why-replywise']) assert.equal(await page.locator(href).count(),1);
    await page.screenshot({ path: `test-results/${name}.png`, fullPage: true });
  }
  await page.route('**/api/generate-reply', route => route.fulfill({ status: 503, json: { error: "We couldn't generate a reply just now. Please try again." } }));
  await page.locator('#use-example').click(); await page.locator('#generate-button').click();
  await page.locator('#form-error').filter({ hasText: "couldn't generate" }).waitFor();
  await page.unroute('**/api/generate-reply');
  await page.route('**/api/generate-reply', route => route.fulfill({ status: 429, json: { error: "You've tried all 5 demo replies. Thanks for testing ReplyWise!" } }));
  used = 5;
  await page.locator('#generate-button').click();
  await page.locator('#form-error').filter({ hasText: 'all 5' }).waitFor();
  await page.waitForFunction(() => document.getElementById('generate-button').disabled);
  assert.equal(await page.locator('#usage').textContent(), '5 of 5 free demo replies used');
  const beforePrototypeGenerations = generations;
  let whatsappRequests = 0;
  page.on('request', request => { if (new URL(request.url()).pathname.startsWith('/api/whatsapp')) whatsappRequests++; });
  await page.reload();
  await page.locator('#wa-prototype-connect').click();
  await page.locator('#wa-connected').waitFor({ state: 'visible' });
  assert.equal(await page.locator('.wa-message').count(), 3);
  assert.match(await page.locator('#wa-state').textContent(), /Demo connected/);
  await page.locator('.wa-message').first().getByRole('button', { name: 'Show sample reply' }).click();
  const sendButton = page.getByRole('button', { name: 'Simulate sending' });
  assert.equal(await sendButton.isDisabled(), true);
  await page.locator('.wa-approve input').check();
  assert.equal(await sendButton.isDisabled(), false);
  await page.locator('.wa-message textarea').fill('TEST edited reviewed reply');
  assert.equal(await sendButton.isDisabled(), true);
  await page.locator('.wa-approve input').check();
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: 'test-results/whatsapp-prototype-mobile.png', fullPage: true });
  await sendButton.click();
  assert.match(await page.locator('#wa-notice').textContent(), /Nothing was sent to WhatsApp/);
  assert.equal(await page.getByRole('button', { name: 'Simulate sending' }).count(), 0);
  await page.locator('#wa-reset-demo').click();
  assert.equal(await page.getByRole('button', { name: 'Show sample reply' }).count(), 3);
  await page.locator('#wa-disconnect').click();
  assert.equal(await page.locator('#wa-prototype-connect').isVisible(), true);
  assert.equal(await page.locator('.wa-message').count(), 0);
  assert.equal(whatsappRequests, 0);
  assert.equal(generations, beforePrototypeGenerations);
  console.info('Browser checks passed: input validation, generation/loading, copy, reset, persistent identity, API errors/cap, four responsive widths, and WhatsApp prototype connect/sample draft/edit/approval/simulated send/reset/disconnect without API calls. API fixtures were mocked.');
} finally { await browser?.close(); child.kill(); }
